#!/bin/bash
USAGE="$(basename "$0") [-h --help] [-c --ctags ] [-v --vim] [-t --tmux] [-w --weechat] [-b --brew]

OPTIONS
        -h, --help
            Print this message

        -c, --ctags
            Install patched ctags

        -v, --vim
            Install VIM plugins & syntax

        -t, --tmux
            Install tmux addons

        -w, --weechat
          Install weechat config

        -z, --zsh
            Install zsh config

        -b, --brew
            Install homebrew & casks\n"
if [[ -z $1 ]]; then
    printf "$USAGE"
    exit 0
fi
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CP="/bin/cp -vfr"

INSTALL_CTAGS=false
INSTALL_VIM=false
INSTALL_ZSH=false
INSTALL_TMUX=false
INSTALL_WEECHAT=false
INSTALL_BREW=false

if ! OPTIONS=$(getopt -o hcvtwabfz -l help,ctags,vim,tmux,weechat,brew,zsh,all -- "$@")
then
    # something went wrong, getopt will put out an error message for us
    exit 1
fi
while [ $# -gt 0 ]; do
    case $1 in
        "-h" | "--help") printf "$USAGE"; exit 0 ;;
        "-c" | "--ctags") INSTALL_CTAGS=true ;;
        "-v" | "--vim") INSTALL_VIM=true ;;
        "-z" | "--zsh") INSTALL_ZSH=true ;;
        "-t" | "--tmux") INSTALL_TMUX=true ;;
        "-w" | "--weechat") INSTALL_WEECHAT=true ;;
        "-b" | "--brew") INSTALL_BREW=true ;;
        "-a" | "--all")
            INSTALL_CTAGS=true
            INSTALL_VIM=true
            INSTALL_TMUX=true
            INSTALL_WEECHAT=true
            INSTALL_BREW=true
            break;;
        (--) shift; break;;
        (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
        (*) break;;
    esac
    shift
done

if $INSTALL_CTAGS; then
    "$DIR/installers/ctags.sh"
fi

if $INSTALL_VIM; then
    "$DIR/installers/vim.sh"
fi

if $INSTALL_ZSH; then
    "$DIR/installers/zsh.sh"
fi

if $INSTALL_TMUX; then
    "$DIR/installers/tmux.sh"
fi

if $INSTALL_WEECHAT; then
    "$DIR/installers/weechat.sh"
fi

if $INSTALL_BREW; then
    "$DIR/installers/brew.sh"
fi

