#!/bin/bash
USAGE="$(basename "$0") [-h --help] [-c --ctags ] [-v --vim] [-t --tmux] [-z --zsh] -- Installs VIM plugins & configures ZSH just the way you like it

OPTIONS
        -h, --help
            Print this message

        -c, --ctags
            Install patched ctags

        -v, --vim
            Install VIM plugins & syntax

        -t, --tmux
            Install tmux addons

        -z, --zsh
            Install ZSH plugins\n"
if [[ -z $1 ]]; then
    printf "$USAGE"
    exit 0
fi
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CP="/bin/cp -vfr"

INSTALL_CTAGS=false
INSTALL_VIM=false
INSTALL_TMUX=false
INSTALL_ZSH_PLUGINS=false

if ! OPTIONS=$(getopt -o hgcmpvtzae -l help,ctags,vim,tmux,zsh,all -- "$@")
then
    # something went wrong, getopt will put out an error message for us
    exit 1
fi
while [ $# -gt 0 ]; do
    case $1 in
        "-h" | "--help") printf "$USAGE"; exit 0 ;;
        "-c" | "--ctags") INSTALL_CTAGS=true ;;
        "-v" | "--vim") INSTALL_VIM=true ;;
        "-t" | "--tmux") INSTALL_TMUX=true ;;
        "-z" | "--zsh") INSTALL_ZSH_PLUGINS=true ;;
        "-a" | "--all")
            INSTALL_CTAGS=true
            INSTALL_VIM=true
            INSTALL_TMUX=true
            INSTALL_ZSH_PLUGINS=true
            break;;
        (--) shift; break;;
        (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
        (*) break;;
    esac
    shift
done

if $INSTALL_TMUX; then
    "$DIR/installers/tmux.sh"
fi

if $INSTALL_CTAGS; then
    "$DIR/installers/ctags.sh"
fi

if $INSTALL_VIM; then
    "$DIR/installers/vim.sh"
fi

if $INSTALL_ZSH_PLUGINS; then
    "$DIR/installers/zsh.sh"
fi

