command_exists () {
  type "$1" &> /dev/null;
}

is_linux () {
    [[ $('uname') == 'Linux' ]];
}

is_osx () {
    [[ $('uname') == 'Darwin' ]]
}

DISABLE_AUTO_TITLE="true"
DISABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="false"

# Load zgen
ZDOTDIR="${HOME}/.zgen"
ZGEN_DIR="$ZDOTDIR/plugins"
source "${HOME}/.zgen/zgen.zsh"

# Check if there's no init script.
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/colored-man
    zgen oh-my-zsh plugins/autojump
    zgen oh-my-zsh plugins/brew
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/git-extras
    zgen oh-my-zsh plugins/node
    zgen oh-my-zsh plugins/npm
    zgen oh-my-zsh plugins/nvm

    # plugins
    zgen load chrissicool/zsh-256color
    zgen load djui/alias-tips
    zgen load rupa/z

    ZGEN_PLUGIN_UPDATE_DAYS=14
    ZGEN_SYSTEM_UPDATE_DAYS=14
    zgen load unixorn/autoupdate-zgen

    zgen load ascii-soup/zsh-url-highlighter
    zgen load willghatch/zsh-hooks

    zgen load unixorn/git-extra-commands

    zgen load zsh-users/zsh-completions src
    zgen load jimmijj/zsh-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search

    if is_osx; then
        zgen load chriskempson/base16-iterm2
    fi

    # theme
    zgen load chriskempson/base16-shell base16-colors.dark.sh
    # zgen load sindresorhus/pure
    BULLETTRAIN_NVM_SHOW=true
    BULLETTRAIN_STATUS_EXIT_SHOW=true
    BULLETTRAIN_GIT_UNTRACKED=" %F{magenta}✭%F{black}"
    zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train
    # zgen load willghatch/zsh-megaprompt
    # zgen load nojhan/liquidprompt

    # save all to init script
    zgen save
fi

ZSH_THEME="bullet-train"

zmodload zsh/terminfo

if is_osx; then
  # zsh-history-substring-search
  # bind UP and DOWN arrow keys
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
elif is_linux; then
  # bind UP and DOWN arrow keys
  zmodload zsh/terminfo
  bindkey "$terminfo[kcuu1]" history-substring-search-up
  bindkey "$terminfo[kcud1]" history-substring-search-down

  # bind P and N for EMACS mode
  bindkey -M emacs '^P' history-substring-search-up
  bindkey -M emacs '^N' history-substring-search-down

  # bind k and j for VI mode
  bindkey -M vicmd 'k' history-substring-search-up
  bindkey -M vicmd 'j' history-substring-search-down
fi

export VISUAL=vim
export GREP_OPTIONS='--color=always'

# User ctrl-z like alt-tab
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# From: http://askubuntu.com/questions/1577/moving-from-bash-to-zsh
autoload -U compinit

for func in $^fpath.zwc(N-.r:); autoload -U -w $func

setopt completeinword
setopt prompt_subst

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*:killall:*' command 'ps -u $USER -o cmd'

autoload select-word-style
select-word-style shell

alias ll='ls -l'
alias la='ls -a'
alias lsa='ls -alh'

HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=5000
setopt incappendhistory
setopt sharehistory
setopt extendedhistory

# superglobs
setopt extendedglob
unsetopt caseglob
unsetopt nomatch 2>/dev/null

setopt auto_cd

# Vi mode
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward

# Allow deleting backwards
# http://www.zsh.org/mla/workers/2008/msg01653.html
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char

KEYTIMEOUT=1 # 10ms for key sequences

alias tmux='tmux -2'

# TMUX
if [[ -z $TMUX ]]; then
  # Attempt to discover a detached session and attach it, else create a new session
  CURRENT_USER=$(whoami)
  if tmux has-session -t $CURRENT_USER 2>/dev/null; then
    tmux -2 attach-session -t $CURRENT_USER
  else
    tmux -2 new-session -s $CURRENT_USER
  fi
fi
