command_exists () {
  type "$1" &> /dev/null;
}

is_linux () {
    [[ $('uname') == 'Linux' ]];
}

is_osx () {
    [[ $('uname') == 'Darwin' ]]
}

DISABLE_AUTO_TITLE="true"
DISABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="false"

# Load zgen
ZDOTDIR="${HOME}/.zgen"
ZGEN_DIR="$ZDOTDIR/plugins"

source "${HOME}/.zgen/zgen.zsh"

function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
}

# Check if there's no init script.
if ! zgen saved; then
  echo "Creating a zgen save"

    # zgen oh-my-zsh
    # zgen oh-my-zsh plugins/sudo
    # zgen oh-my-zsh plugins/command-not-found
    # zgen oh-my-zsh plugins/brew
    # zgen oh-my-zsh plugins/git
    # zgen oh-my-zsh plugins/git-extras
    # zgen oh-my-zsh plugins/node
    # zgen oh-my-zsh plugins/npm

    # Causes startup delays with bullet train
    # zgen oh-my-zsh plugins/nvm

    # plugins
    zgen load djui/alias-tips
    zgen load rupa/z

    ZGEN_PLUGIN_UPDATE_DAYS=14
    ZGEN_SYSTEM_UPDATE_DAYS=14
    zgen load unixorn/autoupdate-zgen

    zgen load unixorn/git-extra-commands

    # zgen load zsh-users/zsh-completions src
    zgen load jimmijj/zsh-syntax-highlighting
    # zgen load zsh-users/zsh-history-substring-search
    zgen load zsh-users/zsh-autosuggestions

    # `fzf`'s “**blah”-completion behaviour, ⌘T, etc.
    zgen load junegunn/fzf shell
    zgen load junegunn/fzf shell/completion.zsh
    zgen load junegunn/fzf shell/key-bindings.zsh

    if is_osx; then
        zgen load chriskempson/base16-iterm2
    fi

    # theme
    zgen load chriskempson/base16-shell base16-colors.dark.sh
    zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train

    # save all to init script
    zgen save
fi

ZSH_THEME="bullet-train"
export BULLETTRAIN_NVM_SHOW=true
export BULLETTRAIN_NVM_FG="black"
export BULLETTRAIN_STATUS_EXIT_SHOW=true
export BULLETTRAIN_GIT_COLORIZE_DIRTY=true
# Git extended can cause slow zsh startup times
export BULLETTRAIN_GIT_EXTENDED=false

zmodload zsh/terminfo

bindkey '^ ' autosuggest-accept

export VISUAL=vim
export GREP_OPTIONS='--color=always'

setopt completeinword
setopt prompt_subst

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*:killall:*' command 'ps -u $USER -o cmd'

autoload select-word-style
select-word-style shell

HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=5000
setopt incappendhistory
setopt sharehistory
setopt extendedhistory

# superglobs
setopt extendedglob
unsetopt caseglob
unsetopt nomatch 2>/dev/null

setopt auto_cd

# Allow c-s to pass through
stty -ixon

# Vi mode
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward

# Allow deleting backwards
# http://www.zsh.org/mla/workers/2008/msg01653.html
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char

KEYTIMEOUT=1 # 10ms for key sequences

alias tmux='tmux -2'

if is_osx; then
  # workaround for https://github.com/neovim/neovim/issues/2048
  export TERMINFO="$HOME/.terminfo"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# GRC colorizes nifty unix tools all over the place
# https://github.com/holman/dotfiles/blob/master/system/grc.zsh
if (( $+commands[grc] )) && (( $+commands[brew] ))
then
  source `brew --prefix`/etc/grc.bashrc
fi

alias ll='colourify ls -l'
alias la='colourify ls -a'
alias lsa='colourify ls -alh'

# This loads nvm
# nvm dramatically slows down zsh startup, use brew install node until https://github.com/creationix/nvm/issues/860 is resolved
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# TMUX
if [[ -z $TMUX ]]; then
  # Attempt to discover a detached session and attach it, else create a new session
  CURRENT_USER=$(whoami)
  if tmux has-session -t $CURRENT_USER 2>/dev/null; then
    tmux -2 attach-session -t $CURRENT_USER
  else
    tmux -2 new-session -s $CURRENT_USER
  fi
fi
